name: Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        continue-on-error: true
        with:
          args: "--output ./docs/lychee/out.md --config ./docs/.lycheerc"

      - name: Get Lychee Exit Code
        id: get-exit-code
        run: echo "lychee_exit_code=$?" >> $GITHUB_ENV

      - name: Create Custom Report
        if: failure()
        run: |
          echo "Lychee doesn't play nice with relative imports for .mdx files. Add a link to the .lycheeignore if needed!" > ./docs/lychee/custom_report.md
          echo "" >> ./docs/lychee/custom_report.md
          cat ./docs/lychee/out.md >> ./docs/lychee/custom_report.md

      - name: Create Issue From File
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./docs/lychee/custom_report.md
          labels: report, automated issue
